### ISSUE TITLE
Did you try this plugin with an Android device?

### ISSUE THREAD

**Issue by amerinoo** [metaflowltd/flutter_health_fit#4]
Hello, after trying to use your plugin (example project) I realized it does not do the autorization correctly so I am not able to test it. I'm using a Oneplus 6T with OxygenOs version 9.0.5.
When I perform the click to the button with the label "Autorize Health", the app shows a dialog  to choose an account, I press my gmail and then dialog disappear but the Authorized boolean is still false and never true.

**Comment by pravinrajmb** [comment]
Same issue

**Comment by jilairan** [comment]
@amerinoo did you set up your OAuth 2.0 Client ID correctly? Cause the issue you are describing could be related to that. I have not used this Plugin myself yet, however I did set up an example project from Google for native Android and encountered a similar problem while not having my Google Project set up correctly. Maybe you want to check out the guide provided by Google: https://developers.google.com/fit/android/get-started

**Comment by amerinoo** [comment]
Hey, that's it. I just needed to set up the OAuth 2.0 Client ID correctly. Problems totally solved!!
